// <auto-generated />
namespace Huerate.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ValueNotRequiredInCustomTranslation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ValueNotRequiredInCustomTranslation));
        
        string IMigrationMetadata.Id
        {
            get { return "201305250422541_ValueNotRequiredInCustomTranslation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
