/*
Huerate - Mobile System for Customer Feedback Collection
Master Thesis at BUT FIT (http://www.fit.vutbr.cz), 2013
Available at http://huerate.cz

Author: Bc. Jakub Kadlubiec, xkadlu00@stud.fit.vutbr.cz or jakub.kadlubiec@gmail.com
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huerate.WebUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Huerate.Services.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter admin.
        /// </summary>
        public static string Action_EnterAdmin {
            get {
                return ResourceManager.GetString("Action_EnterAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Action_Logout {
            get {
                return ResourceManager.GetString("Action_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answers.
        /// </summary>
        public static string Admin_Answers {
            get {
                return ResourceManager.GetString("Admin_Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Admin_Help {
            get {
                return ResourceManager.GetString("Admin_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions results.
        /// </summary>
        public static string Admin_Results {
            get {
                return ResourceManager.GetString("Admin_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to know what your customers want?.
        /// </summary>
        public static string AreYouInterested {
            get {
                return ResourceManager.GetString("AreYouInterested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask them!.
        /// </summary>
        public static string AskThem {
            get {
                return ResourceManager.GetString("AskThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You want to tell us something else?.
        /// </summary>
        public static string Form_AdditionalText {
            get {
                return ResourceManager.GetString("Form_AdditionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel free to add additional comments..
        /// </summary>
        public static string Form_AdditionalTextInstructions {
            get {
                return ResourceManager.GetString("Form_AdditionalTextInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Form_Finish {
            get {
                return ResourceManager.GetString("Form_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You!.
        /// </summary>
        public static string Form_ThankYou {
            get {
                return ResourceManager.GetString("Form_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best.
        /// </summary>
        public static string Form_TheBest {
            get {
                return ResourceManager.GetString("Form_TheBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worst.
        /// </summary>
        public static string Form_TheWorst {
            get {
                return ResourceManager.GetString("Form_TheWorst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We really appreciate Your help..
        /// </summary>
        public static string Form_WeAppreciateYourHelp {
            get {
                return ResourceManager.GetString("Form_WeAppreciateYourHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string General_Contact {
            get {
                return ResourceManager.GetString("General_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string General_Down {
            get {
                return ResourceManager.GetString("General_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string General_Email_Address {
            get {
                return ResourceManager.GetString("General_Email_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string General_LogIn {
            get {
                return ResourceManager.GetString("General_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string General_No {
            get {
                return ResourceManager.GetString("General_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string General_Password {
            get {
                return ResourceManager.GetString("General_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant administration - .
        /// </summary>
        public static string General_RestaurantAdministration {
            get {
                return ResourceManager.GetString("General_RestaurantAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string General_Up {
            get {
                return ResourceManager.GetString("General_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string General_Yes {
            get {
                return ResourceManager.GetString("General_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect customer.
        /// </summary>
        public static string Home_CollectCustomerFeedback_A {
            get {
                return ResourceManager.GetString("Home_CollectCustomerFeedback_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedback.
        /// </summary>
        public static string Home_CollectCustomerFeedback_B {
            get {
                return ResourceManager.GetString("Home_CollectCustomerFeedback_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start by creating your account.
        /// </summary>
        public static string Home_CollectCustomerFeedback1 {
            get {
                return ResourceManager.GetString("Home_CollectCustomerFeedback1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is completely free.
        /// </summary>
        public static string Home_CollectCustomerFeedback2 {
            get {
                return ResourceManager.GetString("Home_CollectCustomerFeedback2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can delete the account anytime.
        /// </summary>
        public static string Home_CollectCustomerFeedback3 {
            get {
                return ResourceManager.GetString("Home_CollectCustomerFeedback3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to everything.
        /// </summary>
        public static string Home_Everything {
            get {
                return ResourceManager.GetString("Home_Everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works on any device.
        /// </summary>
        public static string Home_Feature1_Caption {
            get {
                return ResourceManager.GetString("Home_Feature1_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huerate is a web application. It runs on any smartphone or tablet that has an internet browser..
        /// </summary>
        public static string Home_Feature1_Text {
            get {
                return ResourceManager.GetString("Home_Feature1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily statistics.
        /// </summary>
        public static string Home_Feature2_Caption {
            get {
                return ResourceManager.GetString("Home_Feature2_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results are always available on restaurant’s password protected online account..
        /// </summary>
        public static string Home_Feature2_Text {
            get {
                return ResourceManager.GetString("Home_Feature2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informative &amp; Easy-to-use.
        /// </summary>
        public static string Home_Feature3_Caption {
            get {
                return ResourceManager.GetString("Home_Feature3_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three types of questions provide comprehensive feedback. Answering by touch is quick and fun..
        /// </summary>
        public static string Home_Feature3_Text {
            get {
                return ResourceManager.GetString("Home_Feature3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Home_Features {
            get {
                return ResourceManager.GetString("Home_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works.
        /// </summary>
        public static string Home_HowItWorks {
            get {
                return ResourceManager.GetString("Home_HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account.
        /// </summary>
        public static string Home_HowItWorks1_Caption {
            get {
                return ResourceManager.GetString("Home_HowItWorks1_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It takes no more than three minutes to set it up.
        /// </summary>
        public static string Home_HowItWorks1_Text {
            get {
                return ResourceManager.GetString("Home_HowItWorks1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a unique survey link.
        /// </summary>
        public static string Home_HowItWorks2_Caption {
            get {
                return ResourceManager.GetString("Home_HowItWorks2_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example huerate.com/myrestaurant.
        /// </summary>
        public static string Home_HowItWorks2_Text {
            get {
                return ResourceManager.GetString("Home_HowItWorks2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give the link to customers.
        /// </summary>
        public static string Home_HowItWorks3_Caption {
            get {
                return ResourceManager.GetString("Home_HowItWorks3_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the link or a QR code to lead them to your survey.
        /// </summary>
        public static string Home_HowItWorks3_Text {
            get {
                return ResourceManager.GetString("Home_HowItWorks3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the results.
        /// </summary>
        public static string Home_HowItWorks4_Caption {
            get {
                return ResourceManager.GetString("Home_HowItWorks4_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to your account to see the statistics.
        /// </summary>
        public static string Home_HowItWorks4_Text {
            get {
                return ResourceManager.GetString("Home_HowItWorks4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email or password.
        /// </summary>
        public static string Home_IncorrectEmailOrPassword {
            get {
                return ResourceManager.GetString("Home_IncorrectEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huerate is a touch-based comment card for your restaurant. Collect customer feedback the beautiful way..
        /// </summary>
        public static string Home_Intro {
            get {
                return ResourceManager.GetString("Home_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It’s free and you can delete your account anytime.
        /// </summary>
        public static string Home_ItsFree {
            get {
                return ResourceManager.GetString("Home_ItsFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join our mailing list.
        /// </summary>
        public static string Home_JoinMailingList {
            get {
                return ResourceManager.GetString("Home_JoinMailingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a feature.
        /// </summary>
        public static string Home_RequestFeature {
            get {
                return ResourceManager.GetString("Home_RequestFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We work hard to make Huerate the best tool for collecting customer feedback. {0}Contact us{1} to request a feature you’re missing in the app..
        /// </summary>
        public static string Home_RequestFeature_Text {
            get {
                return ResourceManager.GetString("Home_RequestFeature_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So how was.
        /// </summary>
        public static string Home_SoHowWas {
            get {
                return ResourceManager.GetString("Home_SoHowWas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember login on this computer.
        /// </summary>
        public static string HomePage_RememberLogin {
            get {
                return ResourceManager.GetString("HomePage_RememberLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huerate.com.
        /// </summary>
        public static string Huerate_Title {
            get {
                return ResourceManager.GetString("Huerate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost password.
        /// </summary>
        public static string Lost_Password {
            get {
                return ResourceManager.GetString("Lost_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string NewsletterSubmit {
            get {
                return ResourceManager.GetString("NewsletterSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next day.
        /// </summary>
        public static string NextDay {
            get {
                return ResourceManager.GetString("NextDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display results from {0}..
        /// </summary>
        public static string NextDayTooltip {
            get {
                return ResourceManager.GetString("NextDayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text answers from {0}.
        /// </summary>
        public static string NoTextAnswers {
            get {
                return ResourceManager.GetString("NoTextAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous day.
        /// </summary>
        public static string PrevDay {
            get {
                return ResourceManager.GetString("PrevDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string Restaurant_Create {
            get {
                return ResourceManager.GetString("Restaurant_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Restaurant_Email {
            get {
                return ResourceManager.GetString("Restaurant_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Name.
        /// </summary>
        public static string Restaurant_Name {
            get {
                return ResourceManager.GetString("Restaurant_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Restaurant_Password {
            get {
                return ResourceManager.GetString("Restaurant_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignInPage_OnPageTitle {
            get {
                return ResourceManager.GetString("SignInPage_OnPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in at Huerate.
        /// </summary>
        public static string SignInPage_Title {
            get {
                return ResourceManager.GetString("SignInPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUpPage_OnPageTitle {
            get {
                return ResourceManager.GetString("SignUpPage_OnPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up at Huerate.
        /// </summary>
        public static string SignUpPage_Title {
            get {
                return ResourceManager.GetString("SignUpPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s stay in touch!.
        /// </summary>
        public static string StayInTouch {
            get {
                return ResourceManager.GetString("StayInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text answers from {0}.
        /// </summary>
        public static string TextAnswers {
            get {
                return ResourceManager.GetString("TextAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks!.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update form.
        /// </summary>
        public static string Update_Form {
            get {
                return ResourceManager.GetString("Update_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will let you know what is going on..
        /// </summary>
        public static string WeWillLetYouKnow {
            get {
                return ResourceManager.GetString("WeWillLetYouKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write us..
        /// </summary>
        public static string WriteUs {
            get {
                return ResourceManager.GetString("WriteUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your survey link:.
        /// </summary>
        public static string YourSurveyLink {
            get {
                return ResourceManager.GetString("YourSurveyLink", resourceCulture);
            }
        }
    }
}
